[package]
name = "wsize"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.32.0"
egui = "0.32.0"
egui_extras = "0.32.0"
env_logger = "0.11.8"
glob = "0.3.2"
rayon = "1.10.0"
rfd = "0.15.4"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
walkdir = "2.5.0"
